# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
from sklearn.model_selection import cross_val_score as cvs
from sklearn.model_selection import cross_val_score as cvs
from sklearn import metrics
import numpy as np
import pandas as pd
import sklearn



# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [2]:
from sklearn import datasets
diabetes = datasets.load_diabetes()



Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [3]:
diabetes.keys()



dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [4]:
diabetes.DESCR


'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, blood sugar

What are the variables in this dataset according to the description? List them in the markdown cell below

## age, sex, body mass, index, average blood/pressure, and 6 blood serum measurements

#### Enter your answer here:




Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [5]:


df = pd.DataFrame(data=diabetes.data, 
                  columns=diabetes.feature_names)


df['target'] = diabetes['target']

df.shape

(442, 11)

In [6]:
df.sample()

age       sex       bmi        bp        s1        s2        s3  \
380  0.016281 -0.044642  0.026128  0.058596 -0.060735 -0.044215 -0.013948   

           s4        s5       s6  target  
380 -0.033958 -0.051401 -0.02593    52.0

#Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [7]:
from sklearn.linear_model import LinearRegression 
linear = LinearRegression()
linear

LinearRegression()

Initialize the model in the variable `diabetes_model`

In [8]:
diabetes_model=linear.fit(
    X = df[["age","sex","bmi","bp","s1","s2","s3","s4","s5","s6"]],
    y = df.target)



In the cell below, fit the model and print the intercept and coefficients of the model. 

In [9]:
diabetes_model.coef_



array([ -10.01219782, -239.81908937,  519.83978679,  324.39042769,
       -792.18416163,  476.74583782,  101.04457032,  177.06417623,
        751.27932109,   67.62538639])

In [10]:
diabetes_model.intercept_

152.1334841628965

Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [11]:
import statsmodels.formula.api as smf
test=smf.ols("target ~ age + sex + bmi + bp + s1 + s2 + s3 + s4 + s5 + s6", data=df).fit()
test.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 target   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Thu, 25 May 2023   Prob (F-statistic):           3.83e-62
Time:                        11:47:10   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    152.1335      2.576     59.061      0.000     147.071     157.196
age          -10.0122     59.749     -0.168      0.867    -127.448     107.424
sex         -239.8191     61.222     -3.917      0.000    -360.151    -119.488
bmi          519.8398     66.534      7.813      0.000     389.069     650.610
bp           324.3904     65.422      4.958      0.000     195.805     452.976
s1          -792.1842    416.684     -1.901      0.058   -1611.169      26.801
s2           476.7458    339.035      1.406      0.160    -189.621    1143.113
s3           101.0446    212.533      0.475      0.635    -316.685     518.774
s4           177.0642    161.476      1.097      0.273    -140.313     494.442
s5           751.2793    171.902      4.370      0.000     413.409    1089.150
s6            67.6254     65.984      1.025      0.306     -62.065     197.316
==============================================================================
Omnibus:                        1.506   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.471   Jarque-Bera (JB):                1.404
Skew:                           0.017   Prob(JB):                        0.496
Kurtosis:                       2.726   Cond. No.                         227.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [12]:
df.sample()

age      sex       bmi        bp        s1        s2        s3  \
258  0.078034  0.05068 -0.024529 -0.042395  0.006687  0.052861 -0.069172   

           s4        s5        s6  target  
258  0.080804 -0.037128  0.056912    89.0

#Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [13]:
# Your code here:

auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [14]:
auto.head()



mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [15]:
auto.dtypes



mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [16]:
auto.model_year.max()



82

In [17]:
auto.model_year.min()

70

Check the dataset for missing values and remove all rows containing at least one missing value.

In [18]:
auto.isnull().sum()



mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [19]:
auto.dropna(inplace=True)

In [20]:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     0
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [21]:
auto.cylinders.value_counts()



4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [22]:
auto_2=auto.drop("car_name", axis=1)
auto_2.sample()


mpg  cylinders  displacement  horse_power  weight  acceleration  \
392  27.0          4         151.0         90.0    2950          17.3   

     model_year  
392          82

In [23]:
from sklearn.model_selection import train_test_split
X=auto_2.drop("mpg", axis=1)
y=auto_2["mpg"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [24]:
X_train.shape


(313, 6)

In [25]:
y_train.shape

(313,)

In [26]:
X_test.shape

(79, 6)

Now we will test the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [27]:
linear.fit(X_train, y_train)
linear.coef_



array([-0.22088724,  0.00782635,  0.00844053, -0.00751899,  0.16902311,
        0.75850401])

Next, fit the model in the cell below.

In [28]:
linear.intercept_



-15.562656817991904

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [29]:
y_pred = linear.predict(X_test)
y_pred


array([29.65095959, 28.95947047, 31.2394056 ,  7.32084597,  9.48858666,
       15.85945462, 26.44818262,  4.51235372, 27.16940548, 11.94334238,
       19.67863385, 30.17611487, 33.79919634, 24.54318223, 21.31493562,
       10.9011827 , 19.65170497, 22.22586855, 22.11533867, 23.99627364,
       14.2157228 ,  8.13390243, 31.25104922, 29.80069804, 28.53328647,
       28.21444247, 27.81942023, 25.34391958, 25.34489704, 21.14946428,
       23.3348993 , 26.40527687, 32.37253446, 20.45606077, 31.24012304,
       28.15898123, 29.72424862, 31.87065671,  5.72800918, 10.88060873,
       12.33601259, 25.89840232, 12.91010448, 13.48895967, 29.93783875,
       31.80406765, 13.62681225, 21.90948684, 19.92403732, 29.68648108,
       30.76357934, 30.72190553, 25.26157561, 16.66810407, 25.93312458,
       14.76415924, 24.70783019, 17.14216655, 26.85648148, 20.0499039 ,
       28.90245776,  9.51067632, 29.76374327, 20.00330867, 34.90769227,
       16.37523343, 33.04696242, 16.90897399, 24.21670762, 16.60

In [30]:
print(f"MAE, error: {metrics.mean_absolute_error(y_test, y_pred)}")
print(f"MSE, error: {metrics.mean_squared_error(y_test, y_pred)}")
print(f"RMSE, error: {np.sqrt(metrics.mean_squared_error(y_test, y_pred))}")
print(f"r2: {metrics.r2_score(y_test, y_pred)}")



MAE, error: 2.4905107180080672
MSE, error: 9.804285394996791
RMSE, error: 3.1311795532988507
r2: 0.8142784192942844


#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [31]:
y_test_pred = linear.predict(X_train)
print(f"MAE, error: {metrics.mean_absolute_error(y_train, y_test_pred)}")
print(f"MSE, error: {metrics.mean_squared_error(y_train, y_test_pred)}")
print(f"RMSE, error: {np.sqrt(metrics.mean_squared_error(y_train, y_test_pred))}")
print(f"r2: {metrics.r2_score(y_train, y_test_pred)}")


MAE, error: 2.6829597309892086
MSE, error: 12.14985072000911
RMSE, error: 3.4856635982276187
r2: 0.8050243378738486


# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [43]:

X_train09, X_test09, y_train09, y_test09 = train_test_split(X, y, test_size = 0.1)

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [44]:
auto_model09=linear.fit(X_train09, y_train09)



Compute the predicted values and r squared score for our new model and new sample data.

In [45]:
y_pred09 = linear.predict(X_test09)
print(f"MAE, error: {metrics.mean_absolute_error(y_test09, y_pred09)}")
print(f"MSE, error: {metrics.mean_squared_error(y_test09, y_pred09)}")
print(f"RMSE, error: {np.sqrt(metrics.mean_squared_error(y_test09, y_pred09))}")
print(f"r2: {metrics.r2_score(y_test09, y_pred09)}")

MAE, error: 3.3243414430359066
MSE, error: 16.54711770269814
RMSE, error: 4.067814856000472
r2: 0.7412793781696645


Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [35]:
from sklearn.model_selection import cross_val_score as cvs
from sklearn.feature_selection import RFE
from sklearn.linear_model import Ridge, Lasso

from sklearn.linear_model import SGDRegressor

from sklearn.neighbors import KNeighborsRegressor

from sklearn.ensemble import GradientBoostingRegressor

from sklearn.svm import SVR

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [36]:
X=auto_2.drop("mpg", axis=1)
y=auto_2["mpg"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)




Fit the model and print the ranking

In [37]:
gbr = GradientBoostingRegressor()
rfe = RFE(estimator=gbr, n_features_to_select=3)
model_new=rfe.fit(X_train, y_train)
model_new.ranking_


array([2, 1, 3, 1, 4, 1])

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_train_reduced`, `y_test_reduced`. Use an 80% split.

In [38]:
dict_ = {}
for j, k in zip(model_new.ranking_, X_train.columns):
    dict_[k] = j
dict_



{'cylinders': 2,
 'displacement': 1,
 'horse_power': 3,
 'weight': 1,
 'acceleration': 4,
 'model_year': 1}

In [39]:
auto_2.sample()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
17  21.0          6         200.0         85.0    2587          16.0   

    model_year  
17          70

In [40]:
X=auto_2[["displacement", "horse_power", "weight"]]
y=auto_2["mpg"]
X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = train_test_split(X, y, test_size = 0.2)

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [41]:
auto_model_reduced=linear.fit(X_train_reduced, y_train_reduced)
y_test_pred_reduced = linear.predict(X_test_reduced)


In [42]:

print(f"MAE, error: {metrics.mean_absolute_error(y_test_reduced, y_test_pred_reduced)}")
print(f"MSE, error: {metrics.mean_squared_error(y_test_reduced, y_test_pred_reduced)}")
print(f"RMSE, error: {np.sqrt(metrics.mean_squared_error(y_test_reduced, y_test_pred_reduced))}")
print(f"r2: {metrics.r2_score(y_test_reduced, y_test_pred_reduced)}")

MAE, error: 3.029948498337405
MSE, error: 14.727687379999123
RMSE, error: 3.837666918845241
r2: 0.7451919198079949
